### ISSUE TITLE
[Question] Does this mod also allow text selection?

### ISSUE THREAD

**Issue by Mathiaszero** [AntumMT/mod-listitems#1]
It runs very well so far on 5.3.0. I am considering adding this interesting mod to my private server. It appears that the items will display in chat. Does this mod allow to select text in a way that I can copy and paste?

**Comment by AntumDeluge** [comment]
It's been so long since I messed with Minetest, I don't remember how it works. As far as I know, if the Minetest client doesn't allow copy & paste, then you can't. If the server doesn't already have a saved chat log, there might be a mod that can output it to text or copy the chat log to the clipboard.

**Comment by Mathiaszero** [comment]
Thanks for the reply despite the inactivity. I can try to to figure out in the code how I can retrieve the log data since that is a good suggestion. So to clarify, you have stopped working on this mod?

**Comment by AntumDeluge** [comment]
Not currently, as I had a bunch of other things I was working on. But I am getting the itch again to work with Minetest. No guarantees, but I may start updating it.

Thanks for letting me know that it works with the current server version.

**Comment by Mathiaszero** [comment]
Sounds good.
